{
 "title": "S3 Endpoints Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{endpoint=~\"authenticate_endpoint|create_user|create_bucket|delete_bucket|handle_upload|handle_request\"}) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total Requests (24h)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total[24h]))"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flask_http_error_total" }
   ]
  }
 ]
}