name: Terraform Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch: 

permissions:
  contents: write
  
jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: actions/setup-terraform@v2
        with:
          terraform_version: v1.9.5

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

  packer-validate:
    name: Pacler Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: actions/setup-packer@v2
        with:
          packer_version: v1.11.2

      - name: Packer init
        run: packer init

      - name: Packer validate
        run: packer validate